import React, { useMemo, useState } from 'react';
import { useDemoState } from '../app/DemoContext';
import '../styles/pages/capabilities.css';

const capabilityColumns = [
  {
    key: 'workers',
    title: 'WORKERS',
    subtitle: 'EXECUTION ENVIRONMENTS',
    items: [
      { id: 'codex', name: 'CODEX', meta: '8 / 16', state: 'READY', tone: 'ready', glyph: '▦' },
      { id: 'claude', name: 'CLAUDE CODE', meta: '6 / 8', state: 'READY', tone: 'ready', glyph: '✺' },
      { id: 'local', name: 'LOCAL WORKER', meta: '4 / 8', state: 'READY', tone: 'ready', glyph: '〉_' },
      { id: 'research', name: 'RESEARCH-01', meta: '0 / 4', state: 'AUTH REQUIRED', tone: 'auth', glyph: '▤' },
      { id: 'analysis', name: 'ANALYSIS-02', meta: '2 / 4', state: 'RATE LIMITED', tone: 'limited', glyph: '□' },
    ],
  },
  {
    key: 'models',
    title: 'MODELS',
    subtitle: 'LANGUAGE + MULTIMODAL',
    items: [
      { id: 'claude35', name: 'CLAUDE 3.5', meta: '42K', state: 'READY', tone: 'ready', glyph: '✺' },
      { id: 'claude3opus', name: 'CLAUDE 3 OPUS', meta: '200K', state: 'READY', tone: 'ready', glyph: '✺' },
      { id: 'gpt4o', name: 'GPT-4O', meta: '128K', state: 'RATE LIMITED', tone: 'limited', glyph: '◉' },
      { id: 'llama', name: 'LLAMA 3.1', meta: '128K', state: 'AUTH REQUIRED', tone: 'auth', glyph: '∞' },
      { id: 'embed', name: 'EMBED-3', meta: '8K', state: 'READY', tone: 'ready', glyph: '△' },
      { id: 'vision', name: 'VISION-1', meta: '32K', state: 'READY', tone: 'ready', glyph: '◌' },
    ],
  },
  {
    key: 'skills',
    title: 'SKILLS',
    subtitle: 'AGENT CAPABILITIES',
    items: [
      { id: 'search', name: 'SEARCH', meta: '∞', state: 'READY', tone: 'ready', glyph: '⌕' },
      { id: 'browse', name: 'BROWSE', meta: '∞', state: 'READY', tone: 'ready', glyph: '◎' },
      { id: 'analyze', name: 'ANALYZE', meta: '∞', state: 'READY', tone: 'ready', glyph: '▥' },
      { id: 'synthesize', name: 'SYNTHESIZE', meta: '∞', state: 'READY', tone: 'ready', glyph: '▤' },
      { id: 'code', name: 'CODE', meta: '∞', state: 'READY', tone: 'ready', glyph: '</>' },
      { id: 'plan', name: 'PLAN', meta: '∞', state: 'RATE LIMITED', tone: 'limited', glyph: '♧' },
    ],
  },
  {
    key: 'mcp',
    title: 'MCP',
    subtitle: 'MODEL CONTEXT PROTOCOL',
    items: [
      { id: 'filesystem', name: 'FILESYSTEM', meta: '∞', state: 'READY', tone: 'ready', glyph: '□' },
      { id: 'github', name: 'GITHUB', meta: '∞', state: 'READY', tone: 'ready', glyph: '●' },
      { id: 'postgres', name: 'POSTGRES', meta: '—', state: 'AUTH REQUIRED', tone: 'auth', glyph: '◉' },
      { id: 'web', name: 'WEB', meta: '∞', state: 'READY', tone: 'ready', glyph: '◎' },
      { id: 'memory', name: 'MEMORY', meta: '∞', state: 'READY', tone: 'ready', glyph: '▦' },
      { id: 'slack', name: 'SLACK', meta: '—', state: 'RATE LIMITED', tone: 'limited', glyph: '✣' },
    ],
  },
  {
    key: 'plugins',
    title: 'PLUGINS',
    subtitle: 'EXTENSIONS',
    items: [
      { id: 'pdf', name: 'PDF PARSER', meta: '∞', state: 'READY', tone: 'ready', glyph: '▤' },
      { id: 'scraper', name: 'WEB SCRAPER', meta: '∞', state: 'READY', tone: 'ready', glyph: '▧' },
      { id: 'arxiv', name: 'ARXIV', meta: '∞', state: 'READY', tone: 'ready', glyph: 'X' },
      { id: 'notion', name: 'NOTION', meta: '—', state: 'AUTH REQUIRED', tone: 'auth', glyph: 'N' },
      { id: 'linear', name: 'LINEAR', meta: '∞', state: 'READY', tone: 'ready', glyph: '◉' },
      { id: 'jira', name: 'JIRA', meta: '—', state: 'RATE LIMITED', tone: 'limited', glyph: '↗' },
    ],
  },
  {
    key: 'forged',
    title: 'FORGED TOOLS',
    subtitle: 'GENERATED BY AGENTS',
    items: [
      { id: 'extractor', name: 'DATA EXTRACTOR', meta: '∞', state: 'READY', tone: 'ready', glyph: '▤' },
      { id: 'figure', name: 'FIGURE ANALYZER', meta: '∞', state: 'READY', tone: 'ready', glyph: '▱' },
      { id: 'lit', name: 'LIT REVIEW', meta: '∞', state: 'READY', tone: 'ready', glyph: '▤' },
      { id: 'hypothesis', name: 'HYPOTHESIS TESTER', meta: '—', state: 'AUTH REQUIRED', tone: 'auth', glyph: '⚒' },
      { id: 'simulation', name: 'SIMULATION RUNNER', meta: '—', state: 'RATE LIMITED', tone: 'limited', glyph: '◌' },
      { id: 'custom', name: 'CUSTOM TOOL', meta: '∞', state: 'READY', tone: 'ready', glyph: '⌁' },
    ],
  },
];

function TopologyField({ activeId, connections }) {
  const routes = [
    [58, 112, 278, 98], [58, 210, 275, 228], [58, 322, 276, 358], [58, 434, 276, 484],
    [214, 260, 460, 154], [214, 384, 460, 316], [214, 496, 460, 482],
  ];
  return (
    <div className="capability-topology-field">
      <svg className="capability-topology" viewBox="0 0 500 620" preserveAspectRatio="none" aria-label="Capability routing topology">
        <g className="capability-topology__grid"><path d="M0 86 H500 M0 172 H500 M0 258 H500 M0 344 H500 M0 430 H500 M0 516 H500" /><path d="M80 0 V620 M160 0 V620 M240 0 V620 M320 0 V620 M400 0 V620" /></g>
        {routes.map(([x1, y1, x2, y2], index) => <path key={index} className={`capability-route ${index < connections ? 'is-active' : ''}`} d={`M ${x1} ${y1} C 140 ${y1}, 310 ${y2}, ${x2} ${y2}`} />)}
        <circle className="capability-topology__core" cx="238" cy="324" r="28" />
        <circle className="capability-topology__core-dot" cx="238" cy="324" r="6" />
        {['W', 'M', 'S', 'M', 'P', 'T'].map((label, index) => <g key={label + index} className={activeId === ['codex', 'claude35', 'search', 'filesystem', 'pdf', 'extractor'][index] ? 'is-selected' : ''}><circle cx={index < 3 ? 74 : 424} cy={96 + index * 88} r="10" /><text x={index < 3 ? 74 : 424} y={100 + index * 88} textAnchor="middle">{label}</text></g>)}
      </svg>
      <div className="capability-topology__labels"><span>INPUT / WORKERS</span><span>ROUTE CORE</span><span>OUTPUT / TOOLS</span></div>
      <p className="capability-topology__caption">ROUTING TOPOLOGY<br />REPRESENTS CAPABILITY FLOW.<br /><small>— SENSE<br />— REASON<br />— PLAN<br />— TOOL<br />— ACT</small></p>
    </div>
  );
}

function CapabilityColumn({ column, selectedId, onSelect }) {
  return (
    <section className="capability-column">
      <header><h2>{column.title}</h2><p>{column.subtitle}</p></header>
      <ol>
        {column.items.map((item, index) => (
          <li key={item.id}>
            <button type="button" className={`capability-item ${selectedId === item.id ? 'is-selected' : ''}`} onClick={() => onSelect(item)} aria-pressed={selectedId === item.id}>
              <span className="capability-item__glyph">{item.glyph}</span>
              <span className="capability-item__copy"><strong>{item.name}</strong><small><i className={`capability-dot is-${item.tone}`} />{item.state}</small><em>{item.meta}</em></span>
              <span className="capability-item__menu">⋮</span>
            </button>
          </li>
        ))}
      </ol>
      <button type="button" className="capability-column__add" onClick={() => onSelect({ id: `${column.key}-new`, name: `NEW ${column.title.slice(0, -1)}`, state: 'DRAFT', tone: 'auth', glyph: '+' })}>＋ ADD {column.title.slice(0, -1)}</button>
    </section>
  );
}

export default function CapabilitiesPage() {
  const { state } = useDemoState();
  const [selected, setSelected] = useState(capabilityColumns[0].items[0]);
  const [connections, setConnections] = useState(4);
  const [notice, setNotice] = useState('SELECT A MODULE TO VIEW DETAILS.');
  const selectedDetails = useMemo(() => selected || capabilityColumns[0].items[0], [selected]);

  const select = (item) => {
    setSelected(item);
    setNotice(`${item.name} / ${item.state}`);
  };

  return (
    <div className="capabilities-page">
      <header className="capabilities-hero">
        <div><p className="capabilities-kicker">AOS / SYSTEM REGISTRY / {state.run.id}</p><h1>CAPABILITIES</h1></div>
        <p className="capabilities-hero__thesis">MODELS.<br />TOOLS.<br />CONNECTIONS.<br /><span>REAL WORK.</span></p>
        <div className="capabilities-hero__context"><p>CONFIGURE WORKER HARNESSES,<br />MODELS, SKILLS, PLUGINS,<br />MCP SERVERS, AND GENERATED TOOLS.</p><span /><p>THE BLACK ATLAS<br />AOS v0.1.0</p></div>
        <div className="capabilities-hero__branch"><span>RESEARCH BRANCH</span><strong>NEURAL INTERFACES⌄</strong><small>12 CONNECTIONS<br />3 WORKERS ONLINE<br />CONTEXT BUDGET&nbsp; 62%</small><i><b /></i></div>
      </header>

      <main className="capabilities-field">
        <TopologyField activeId={selectedDetails.id} connections={connections} />
        <div className="capabilities-columns">
          {capabilityColumns.map((column) => <CapabilityColumn key={column.key} column={column} selectedId={selectedDetails.id} onSelect={select} />)}
        </div>
      </main>

      <section className="capabilities-bottom">
        <div className="capabilities-routes"><h2>ACTIVE ROUTES</h2><p><i /> WORKER CODEX <b>→</b> MODEL CLAUDE 3.5 <b>→</b> SKILL ANALYZE <b>→</b> MCP FILESYSTEM <b>→</b> TOOL FIGURE ANALYZER</p><p><i /> WORKER LOCAL WORKER <b>→</b> MODEL LLAMA 3.1 <b>→</b> SKILL CODE <b>→</b> PLUGIN GITHUB <b>→</b> TOOL DATA EXTRACTOR</p><p><i /> WORKER CLAUDE CODE <b>→</b> MODEL CLAUDE 3 OPUS <b>→</b> SKILL SYNTHESIZE <b>→</b> PLUGIN ARXIV <b>→</b> TOOL LIT REVIEW</p></div>
        <div className="capabilities-actions"><button type="button" onClick={() => { setConnections((count) => count + 1); setNotice('CONNECTION ADDED / ROUTE PENDING'); }}>↗ ADD CONNECTION</button><button type="button" onClick={() => setNotice('FORGE TOOL / DRAFT CREATED')}>⚒ FORGE TOOL</button><button type="button" onClick={() => setNotice('CAPABILITY TEST / SIMULATED PASS')}>▶ TEST CAPABILITY</button></div>
        <aside className="capabilities-inspector"><span className="telemetry">{selectedDetails.id.toUpperCase()} / SELECTED MODULE</span><h2>{selectedDetails.name}</h2><p>{notice}</p><dl><div><dt>STATE</dt><dd>{selectedDetails.state}</dd></div><div><dt>ROUTE CAPACITY</dt><dd>{selectedDetails.meta}</dd></div><div><dt>LAST CHECK</dt><dd>00:02:14 AGO</dd></div></dl></aside>
      </section>
    </div>
  );
}
